### ISSUE TITLE
mark Java declarations native("jvm") in the model loader

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-model#11]
For some reason that I simply don't understand, after a couple of bites at the cherry, @chochos has still not been able to solve ceylon/ceylon-js#637.

But it strikes me that the backend is now the wrong place for this error checking to be done _anyway_. If the model loader where to mark Java stuff as `native("jvm")`, wouldn't we get those checks for free, during typechecking?

@quintesse?

**Comment by quintesse** [comment]
All native elements are already marked that way in the `car` files and the JVM model loader loads those.

**Comment by FroMage** [comment]
I think he means "Java types that don't come from Ceylon", like the JDK.

**Comment by quintesse** [comment]
Even those are marked "native" by the model loader

**Comment by gavinking** [comment]
@quintesse then I don't understand why the typechecker doesn't produce an error when I try to extend a Java class in JS.

**Comment by gavinking** [comment]
OK, actually the case I'm talking about is the case where you have a Java class in the _same_ project as the Ceylon source. Those are not marked `native`.

**Comment by quintesse** [comment]
Yes, I'm looking into that right now. See if I can get the model loader to mark those native as well.

**Comment by quintesse** [comment]
I'm not sure we'd get _all_ the checks for free but I agree those checks shouldn't be made in the JS compiler.

**Comment by gavinking** [comment]
Well we don't get all the checks for free because of bug ceylon/ceylon-spec/issues/1436 i.e. a lot of stuff is simply not checked. But it needs to be.
