### ISSUE TITLE
Use Maven

### ISSUE THREAD

**Issue by ftomassetti** [ceylon/ceylon-model#13]
In my opinion it would be great to use maven for retrieve dependencies (include your jar of junit it is... an outdated practice) and make this library available on Maven Central. You can easily do that using OSSHR Nexus. Let me know if I can help.

**Comment by FroMage** [comment]
Making our distrib available on Maven Central is a nice idea, we haven't got time yet, though. But it's an issue for the distrib, so I'll move it there: https://github.com/ceylon/ceylon-dist/issues/54

Thanks.
