### ISSUE TITLE
TypeLexer + TypeParser need to learn defaulted parameters

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-model#3]
> Missing expected token: CLOSE_PAR, got: WORD[=] at CeylonAstType(RedHatType, ceylon.language::Anything(com.redhat.ceylon.compiler.typechecker.tree::Node, ceylon.ast.core::Node)=)

(This is uncommitted ceylon.ast WIP; I’ll add an independent test case later.)

**Comment by lucaswerkmeister** [comment]
In module `tmp`:

``` ceylon
shared Anything(Anything=) a = nothing;
```

In module `tmp2`:

``` ceylon
import tmp { a }
shared void run() {
    value v = `a`;
}
```

> Error while resolving type of toplevel attribute for `tmp::a`: Could not find type `ceylon.language.Anything=`

Different error message because the lexer just lumps the `=` into the `Anything` token, but it’s the same bug / missing feature.

**Comment by lucaswerkmeister** [comment]
Status update: I have implemented this, but it seems to cause some unexpected test failures (some generated code differring from expected code, some really weird assignability errors). A lot of errors however seem to be fallout from the lc constructors merge, so since this isn’t terribly urgent, I think I’ll wait a bit until that’s been improved before I investigate these test failures.

**Comment by lucaswerkmeister** [comment]
Unassigning myself from this issue. I have something in #4 and ceylon/ceylon-compiler#2227, but the remaining errors I don’t understand, so someone else will have to fix those. Sorry.

**Comment by FroMage** [comment]
I merged it manually after tweaking it, thanks!

**Comment by lucaswerkmeister** [comment]
Great, thanks!
