### ISSUE TITLE
bug in TypePrinter

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-model#6]
`TypePrinter` renders the type `Tuple<Nothing,Nothing,Empty & Tuple<Nothing,Nothing,Empty>>` as `Nothing[2]`.

**Comment by pthariensflame** [comment]
Well, they _are_ equal as types.  :)

**Comment by gavinking** [comment]
Hrm. Well that's true _now_, in light of ceylon/ceylon-spec#1387, since `[Nothing]` is now the same type as `Nothing`.

But actually it wasn't correct before...

**Comment by gavinking** [comment]
There's still a problem: `Tuple<Integer,Integer,Empty & Tuple<Integer,Integer,Empty>>` is rendered as `Integer[2]`.

**Comment by gavinking** [comment]
Fixed.
